version: '3.1'

services:

  mongo:
    image: mongo
    ports:
       - "27017:27017"



  ynginx:
      image: img-utube-nginx:2018
      depends_on:
       - yremote
      ports:
       - "80:80"
       - "443:443"
       - "81:81"


  yremote:
       image: img-utube-remote:2018
       depends_on:
        - mongo
       ports:
        - "3000:3000"
