#  version: "3"
#services:

  mongodb:
      image: mongo

      ports:
       - "27017:27017"

  yremote:
      image: localhost:5000/utube/yremote:2018

      links:
       - mongodb
      ports:
       - "3000:3000"

  ynginx:
      image: localhost:5000/utube/ynginx:2018

      links:
       - yremote
      ports:
       - "80:80"
       - "443:443"
       - "81:81"
