apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ynginx
  name: ynginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ynginx
    spec:
      containers:
      - image: localhost:5000/utube/ynginx:2018
        name: ynginx
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 81
        resources: {}
      restartPolicy: Always
status: {}
