apiVersion: v1
kind: Service
metadata:
  name: yremoteservice
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3001
#    nodePort: 30012
  selector:
    app: yremote
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yremote
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: yremote
    spec:

      containers:
      - image: localhost:5000/utube/yremote:2018
        name: yremote
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 3000



