apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: yremote
  name: yremote
spec:
  replicas: 5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: yremote
    spec:
      containers:
      - image: localhost:5000/utube/yremote:2018
        name: yremote
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
