---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yremote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yremote
    spec:
      containers:
      - name: yremote
        image: img-utube-remote:2018
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
#       livenessProbe:
#          initialDelaySeconds: 5
#          periodSeconds: 5
#          httpGet:
#            path: /health
#            port: 8080
#        resources:
#          limits:
#            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: yremote
spec:
  ports:
  - nodePort: 32767
    port: 80
    targetPort: 3000
  selector:
    app: mongo
    tier: yremote
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: web
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
        resources:
          limits:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ynginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ynginx
    spec:
      containers:
      - name: ynginx
        image: img-utube-nginx:2018
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
#       livenessProbe:
#          initialDelaySeconds: 5
#          periodSeconds: 5
#          httpGet:
#            path: /health
#            port: 8080
#        resources:
#          limits:
#            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ynginx
spec:
  ports:
  - nodePort: 32766
    port: 80
    targetPort: 8080
  selector:
      app: ynginx
  type: NodePort
